import { ICardAffiliateProps } from "@Components/molecules/CardAffiliate";
import { ICardLevelState } from "@Components/molecules/CardLevel";

export const DataLevel: ICardLevelState[] = [
  {
    level: 1,
    status: "done",
    nextLevel: 0,
    completed: 3,
    total: 3,
    data: [
      {
        index: 1,
        name: "Qualify after investment",
        value: "$300/300",
        done: true,
      },
      {
        index: 1,
        name: "2 tier direct commission",
        value: "5/2",
        done: true,
      },
      {
        index: 1,
        name: "Maximum binary tree income",
        value: "$400/200",
        done: true,
      },
    ],
  },
  {
    level: 2,
    status: "done",
    nextLevel: 0,
    completed: 4,
    total: 4,
    data: [
      {
        index: 1,
        name: "Condition with 6 F1 or more",
        value: "06/06",
        done: true,
      },
      {
        index: 1,
        name: "There are total tree sales",
        value: "$14000/12000",
        done: true,
      },
      {
        index: 1,
        name: "3 tier direct commission",
        value: "04/03",
        done: true,
      },
      {
        index: 1,
        name: "Maximum binary tree income",
        value: "$600/400",
        done: true,
      },
    ],
  },
  {
    level: 3,
    status: "pending",
    nextLevel: 1,
    completed: 3,
    total: 4,
    data: [
      {
        index: 1,
        name: "Personal investment",
        value: "$1100/1200",
        done: false,
      },
      {
        index: 1,
        name: "There are total tree sales",
        value: "$7500/60.000",
        done: true,
      },
      {
        index: 1,
        name: "Including 3 F1s reaching Level 2",
        value: "04/03",
        done: true,
      },
      {
        index: 1,
        name: "4 tier direct commission",
        value: "06/04",
        done: true,
      },
      {
        index: 1,
        name: "Maximum binary tree income",
        value: "$800/600",
        done: true,
      },
    ],
  },
  {
    level: 4,
    status: "disabled",
    nextLevel: 0,
    completed: 0,
    total: 5,
    data: [
      {
        index: 1,
        name: "Personal investment",
        value: "$2300/2400",
        done: false,
      },
      {
        index: 1,
        name: "There are total tree sales",
        value: "$400.000/300.000",
        done: false,
      },
      {
        index: 1,
        name: "Including 3 F1s reaching Level 3",
        value: "04/03",
        done: false,
      },
      {
        index: 1,
        name: "6 tier direct commission",
        value: "07/06",
        done: false,
      },
      {
        index: 1,
        name: "Maximum binary tree income",
        value: "$900/800",
        done: false,
      },
    ],
  },
  {
    level: 5,
    status: "disabled",
    nextLevel: 0,
    completed: 0,
    total: 5,
    data: [
      {
        index: 1,
        name: "Personal investment",
        value: "$4.000/4.800",
        done: false,
      },
      {
        index: 1,
        name: "There are total tree sales",
        value: "$2.000.000/1.800.000",
        done: false,
      },
      {
        index: 1,
        name: "Including 3 F1s reaching Level 4",
        value: "06/03",
        done: false,
      },
      {
        index: 1,
        name: "8 tier direct commission",
        value: "09/08",
        done: false,
      },
      {
        index: 1,
        name: "Maximum binary tree income",
        value: "$1.500/1.200",
        done: false,
      },
    ],
  },
  {
    level: 6,
    status: "disabled",
    nextLevel: 0,
    completed: 0,
    total: 5,
    data: [
      {
        index: 1,
        name: "Personal investment",
        value: "$11.000/12.000",
        done: false,
      },
      {
        index: 1,
        name: "There are total tree sales",
        value: "$10.000.000/9.000.000",
        done: false,
      },
      {
        index: 1,
        name: "Including 3 F1s reaching Level 5",
        value: "03/03",
        done: false,
      },
      {
        index: 1,
        name: "10 tier direct commission",
        value: "10/10",
        done: false,
      },
      {
        index: 1,
        name: "Maximum binary tree income",
        value: "$1.700/1.600",
        done: false,
      },
    ],
  },
  {
    level: 7,
    status: "disabled",
    nextLevel: 0,
    completed: 0,
    total: 5,
    data: [
      {
        index: 1,
        name: "Personal investment",
        value: "$11.000/12.000",
        done: false,
      },
      {
        index: 1,
        name: "There are total tree sales",
        value: "$50M/50M",
        done: false,
      },
      {
        index: 1,
        name: "Including 3 F1s reaching Level 6",
        value: "03/03",
        done: false,
      },
      {
        index: 1,
        name: "12 tier direct commission",
        value: "12/21",
        done: false,
      },
      {
        index: 1,
        name: "Maximum binary tree income",
        value: "$2.000/2.000",
        done: false,
      },
    ],
  },
];
export const DataAffiliate: ICardAffiliateProps[] = [
  {
    index: 1,
    members: 29,
    amount: 304,
    status: "active",
  },
  {
    index: 2,
    members: 29,
    amount: 102,
    status: "active",
  },
  {
    index: 3,
    members: 29,
    amount: 400,
    status: "pending",
  },
  {
    index: 4,
    members: 29,
    amount: 40,
    status: "active",
  },
  {
    index: 5,
    members: 29,
    amount: 304,
    status: "active",
  },
  {
    index: 6,
    members: 29,
    amount: 304,
    status: "active",
  },
  {
    index: 7,
    members: 29,
    amount: 304,
    status: "active",
  },
  {
    index: 8,
    members: 29,
    amount: 304,
    status: "active",
  },
  {
    index: 9,
    members: 29,
    amount: 304,
    status: "active",
  },
  {
    index: 10,
    members: 29,
    amount: 304,
    status: "active",
  },
  {
    index: 11,
    members: 29,
    amount: 304,
    status: "active",
  },
  {
    index: 12,
    members: 29,
    amount: 304,
    status: "disabled",
  },
  {
    index: 13,
    members: 29,
    amount: 304,
    status: "disabled",
  },
  {
    index: 14,
    members: 29,
    amount: 304,
    status: "disabled",
  },
  {
    index: 15,
    members: 29,
    amount: 304,
    status: "disabled",
  },
  {
    index: 16,
    members: 29,
    amount: 304,
    status: "disabled",
  },
  {
    index: 17,
    members: 29,
    amount: 304,
    status: "disabled",
  },
  {
    index: 18,
    members: 29,
    amount: 304,
    status: "disabled",
  },
  {
    index: 19,
    members: 29,
    amount: 304,
    status: "disabled",
  },
  {
    index: 20,
    members: 29,
    amount: 304,
    status: "disabled",
  },
  {
    index: 21,
    members: 29,
    amount: 304,
    status: "disabled",
  },
  {
    index: 22,
    members: 29,
    amount: 304,
    status: "disabled",
  },
  {
    index: 23,
    members: 29,
    amount: 304,
    status: "disabled",
  },
  {
    index: 24,
    members: 29,
    amount: 304,
    status: "disabled",
  },
];

export const infoData = {
  id: 8695,
  level: 2,
  package: 300,
  partners: 24,
  profit: 24,
  date: "18:04:45 19, Feb 2020",
};

export const listAffiliate = [
  {
    id: 1,
    name: "f1",
    list: [
      "3245",
      "5743",
      "2365",
      "2324",
      "3254",
      "3245",
      "5743",
      "2365",
      "2324",
      "3254",
    ],
  },
  {
    id: 1,
    name: "f1",
    list: [
      "3245",
      "5743",
      "2365",
      "2324",
      "3254",
      "3245",
      "5743",
      "2365",
      "2324",
      "8478",
    ],
  },
  {
    id: 2,
    name: "f2",
    list: [
      "3245",
      "5743",
      "2365",
      "2324",
      "3254",
      "3245",
      "5743",
      "2365",
      "3254",
    ],
  },
  {
    id: 3,
    name: "f3",
    list: ["3245", "5743", "2365", "2324", "3254", "3245", "5743", "2324"],
  },
  {
    id: 4,
    name: "f4",
    list: ["3245", "5743", "2365", "2324", "3254", "3245", "2365"],
  },
  {
    id: 5,
    name: "f5",
    list: ["3245", "5743", "2365", "2324", "3254", "3245", "5743"],
  },
  {
    id: 6,
    name: "f6",
    list: ["3245", "5743", "2365", "2324", "3254", "3245"],
  },
  {
    id: 7,
    name: "f7",
    list: ["3245", "5743", "2365", "2324", "3254"],
  },
  {
    id: 8,
    name: "f8",
    list: ["3245", "5743", "2365", "2324"],
  },
  {
    id: 9,
    name: "f9",
    list: ["3245", "5743", "2365"],
  },
  {
    id: 10,
    name: "f10",
    list: ["3245", "5743"],
  },
];
