export const ACCOUNT_ACTION = {
    LOGIN_REQUEST: 'ACCOUNT_LOGIN_REQUEST',
    LOGOUT_REQUEST: 'ACCOUNT_LOGOUT_REQUEST',

    LOGIN_SUCCESS: 'ACCOUNT_LOGIN_SUCCESS',
    LOGIN_FAIL: 'ACCOUNT_LOGIN_FAIL',
    LOGOUT: "ACCOUNT_LOGOUT",
   
    AUTHEN_ENABLED: "ACCOUNT_AUTHEN_ENABLED",
    AUTHEN_DISABLED: "ACCOUNT_AUTHEN_DISABLED"
}
