export const ACCOUNT_ACTION = {
  LOGIN_REQUEST: "ACCOUNT_LOGIN_REQUEST",
  LOGOUT_REQUEST: "ACCOUNT_LOGOUT_REQUEST",

  LOGIN_SUCCESS: "ACCOUNT_LOGIN_SUCCESS",
  LOGIN_FAIL: "ACCOUNT_LOGIN_FAIL",
  LOGOUT: "ACCOUNT_LOGOUT"
};
